# Generated by Django 3.2.5 on 2021-08-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(blank=True, max_length=5, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('currentPrice', models.FloatField()),
                ('marketCap', models.FloatField()),
                ('enterpriseValue', models.FloatField()),
                ('forwardPE', models.FloatField()),
                ('enterpriseToRev', models.FloatField()),
                ('enterpriseToEbitda', models.FloatField()),
                ('profitMargins', models.FloatField()),
                ('roe', models.FloatField()),
            ],
        ),
    ]
